server:
  port: 8080

spring:
  application:
    name: trackerpro
  
  # H2 Database Configuration (for testing)
  datasource:
    url: jdbc:h2:mem:trackerpro
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # MySQL Configuration (commented out, uncomment when switching to MySQL)
  # datasource:
  #   url: jdbc:mysql://localhost:3306/trackerpro
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   username: root
  #   password: password
  
  jpa:
    database: h2
    # database: mysql # Uncomment when switching to MySQL
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        # dialect: org.hibernate.dialect.MySQL8Dialect # Uncomment when switching to MySQL
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

logging:
  level:
    com.webapp.trackerpro: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# Custom application properties
app:
  admin:
    email: admin@trackerpro.com
    password: admin123